services:
  new-etl:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # LOG_LEVEL: debug | info | warning | error (debug = all logs)
      - LOG_LEVEL=debug
