apiVersion: v1
kind: Service
metadata:
  name: etl-service
  labels:
    app: mantrixflow-etl
spec:
  selector:
    app: mantrixflow-etl
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
